# .github/workflows/docker-ci.yml
name: CI Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    name: Build & Push multi-arch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (pour multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Docker/
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/arte/formation:latest
          # Cache des couches et des mounts BuildKit via GitHub Actions Cache
          cache-from: type=gha
          cache-to:   type=gha,mode=max
